### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by zachthedev** [Nass-O/DarkTube#8]
@Nass-O Hey! I have been using DarkTube v3 for quite some time now. For some reason I just checked userstyles and v3 was deleted and I saw that you are working on v4. What do you think is the eta on that? Thanks and keep up the great work!

**Comment by Nass-O** [comment]
Hey !

There is no official ETA but i'd say we'll release the V4 in a month or less

**Comment by zachthedev** [comment]
@Nass-O Awesome! When it is completed could you just reply to this so I know when to download it?Thanks!

**Comment by Nass-O** [comment]
If i remember lol i'll try !
